environment: development
chdir: /var/www/app
address: 127.0.0.1
user: www-data
group: www-data
port: 14000
pid: /var/www/app/thin.pid
rackup: /var/www/app/config.ru
log: /var/www/app/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true

